#pragma once

#include <iostream>
#include <sstream>
#include <assert.h>
#include <string>
#include <vector>
#include <map>
#include <set>
#include <stack>
#include <queue>
#include <list>
#include <unordered_map>
#include <unordered_set>
#include <algorithm>
#include <utility>
#include <memory>
#include <type_traits>
#include <typeindex>
#include <exception>
#include <chrono>
#include <functional>
#include <random>
#include <stdexcept>
#include <cmath>
#include <limits>
#include <thread>
#include <mutex>
#include <condition_variable>
#include "Traits.hpp"

//more .h here...

#include "Defines.h"
#include "CheckMemberExist.h"
#include "AlignedAlloc.h"
#include "Random.h"
#include "Singleton.h"
#include "Pair.h"
#include "Function.h"
#include "Utils.h"
#include "StopWatch.h"
#include "dtoa_milo.h"
#include "Vector.h"
#include "String.h"
#include "Stack.h"
#include "Queue.h"
#include "PriorityQueue.h"
#include "MemoryPool.h"
#include "HashSet.h"
#include "List.h"
#include "RBTree.h"
#include "RBTree2.h"
#include "Set.h"
#include "Map.h"
#include "HashMap.h"
#include "Dictionary.h"
#include "SkipList.h"
#include "Serialization.h"
#include "Variant.h"
#include "Console.h"
#include "AVLTree.h"

//more .hpp here...
#include "Utils.hpp"
#include "String.hpp"
#include "Vector.hpp"
#include "Stack.hpp"
#include "Queue.hpp"
#include "PriorityQueue.hpp"
#include "HashSet.hpp"
#include "List.hpp"
#include "RBTree.hpp"
#include "RBTree2.hpp"
#include "Set.hpp"
#include "Map.hpp"
#include "HashMap.hpp"
#include "Dictionary.hpp"
#include "SkipList.hpp"
#include "CMHashMap.hpp"
#include "CMHashSet.hpp"
#include "Serialization.hpp"
#include "Any.hpp"
#include "Console.hpp"
#include "Aspect.hpp"
#include "RedBlackTree.hpp"
#include "ContiguousMemoryHash.h"
#include "SizeBalanceTree.hpp"
#include "BppTree.hpp"
#include "AVLTree.hpp"
#include "SharedPtr.hpp"
#include "Timer.hpp"
#include "Tuple.hpp"

