#pragma once

#include "../AjyLib.h"
using namespace std;
using namespace Ajy;

// test
#include "Traits_Test.h"
#include "Other_Test.h"
#include "String_Test.h"
#include "Vector_Test.h"
#include "Stack_Test.h"
#include "Queue_Test.h"
#include "PriorityQueue_Test.h"
#include "List_Test.h"
#include "Map_Test.h"
#include "MultiMap_Test.h"
#include "Set_Test.h"
#include "MultiSet_Test.h"
#include "HashMap_Test.h"
#include "HashSet_Test.h"
#include "Dictionary_Test.h"
#include "Variant_Test.h"
#include "Serialization_Test.h"
#include "MemoryPoolTest.h"
#include "SkipList_Test.h"
#include "MakeIndexSequence_Test.h"
#include "Any_Test.h"
#include "CMHashMap_Test.h"
#include "CMHashSet_Test.h"
#include "RedBlackTree_Test.h"
#include "CacheAffinityHash_Test.h"
#include "SizeBalanceTree_Test.h"
#include "BppTree_Test.h"
#include "AVLTree_Test.h"
#include "SharedPtr_Test.h"
#include "TimerTest.h"
#include "CheckMember_Test.h"
#include "Tuple_Test.h"
#include "TypeList_Test.h"
#include "Bind_Test.h"
#include "Function_Test.h"


// compare
#include "Vector_Compare.h"
#include "List_Compare.h"
#include "HashMap_Compare.h"
#include "HashMultiMap_Compare.h"
#include "HashSet_Compare.h"
#include "HashMultiSet_Compare.h"
#include "Map_Compare.h"
#include "Multimap_Compare.h"
#include "Set_Compare.h"
#include "MultiSet_Compare.h"
